# Generated by Django 5.0.3 on 2024-03-30 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('tuberculosis', models.BooleanField(default=False)),
                ('prct_tuberculosis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prct_no_tuberculosis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
